TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += bk9130B.db
DB += bk9130B.proto

#=======================================
include $(TOP)/configure/RULES
